//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 03:35:46 PM CET 
//


package com.livejournal.fbbooks;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * An epigraph
 * 
 * <p>Java class for epigraphType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="epigraphType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="p" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType"/>
 *           &lt;element name="poem" type="{http://www.gribuser.ru/xml/fictionbook/2.0}poemType"/>
 *           &lt;element name="cite" type="{http://www.gribuser.ru/xml/fictionbook/2.0}citeType"/>
 *           &lt;element name="empty-line" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;/choice>
 *         &lt;element name="text-author" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "epigraphType", propOrder = {
    "pOrPoemOrCite",
    "textAuthor"
})
public class EpigraphType {

    @XmlElements({
        @XmlElement(name = "p", type = PType.class),
        @XmlElement(name = "poem", type = PoemType.class),
        @XmlElement(name = "cite", type = CiteType.class),
        @XmlElement(name = "empty-line")
    })
    protected List<Object> pOrPoemOrCite;
    @XmlElement(name = "text-author")
    protected List<PType> textAuthor;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the pOrPoemOrCite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pOrPoemOrCite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOrPoemOrCite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PType }
     * {@link PoemType }
     * {@link CiteType }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPOrPoemOrCite() {
        if (pOrPoemOrCite == null) {
            pOrPoemOrCite = new ArrayList<Object>();
        }
        return this.pOrPoemOrCite;
    }

    /**
     * Gets the value of the textAuthor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textAuthor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PType }
     * 
     * 
     */
    public List<PType> getTextAuthor() {
        if (textAuthor == null) {
            textAuthor = new ArrayList<PType>();
        }
        return this.textAuthor;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
