//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 03:35:46 PM CET 
//


package com.livejournal.fbbooks;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shareModesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="shareModesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="free"/>
 *     &lt;enumeration value="paid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "shareModesType")
@XmlEnum
public enum ShareModesType {

    @XmlEnumValue("free")
    FREE("free"),
    @XmlEnumValue("paid")
    PAID("paid");
    private final String value;

    ShareModesType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShareModesType fromValue(String v) {
        for (ShareModesType c: ShareModesType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
