//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 03:35:46 PM CET 
//


package com.livejournal.fbbooks;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "title-infoType", propOrder = {
    "genre",
    "author",
    "bookTitle",
    "annotation",
    "keywords",
    "date",
    "coverpage",
    "lang",
    "srcLang",
    "translator",
    "sequence"
})
public class TitleInfoType {

    @XmlElement(required = true)
    protected List<TitleInfoType.Genre> genre;
    @XmlElement(required = true)
    protected List<TitleInfoType.Author> author;
    @XmlElement(name = "book-title", required = true)
    protected TextFieldType bookTitle;
    protected AnnotationType annotation;
    protected TextFieldType keywords;
    protected DateType date;
    protected TitleInfoType.Coverpage coverpage;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;
    @XmlElement(name = "src-lang")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String srcLang;
    protected List<AuthorType> translator;
    protected List<SequenceType> sequence;

    /**
     * Gets the value of the genre property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genre property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenre().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleInfoType.Genre }
     * 
     * 
     */
    public List<TitleInfoType.Genre> getGenre() {
        if (genre == null) {
            genre = new ArrayList<TitleInfoType.Genre>();
        }
        return this.genre;
    }

    /**
     * Gets the value of the author property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the author property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleInfoType.Author }
     * 
     * 
     */
    public List<TitleInfoType.Author> getAuthor() {
        if (author == null) {
            author = new ArrayList<TitleInfoType.Author>();
        }
        return this.author;
    }

    /**
     * Gets the value of the bookTitle property.
     * 
     * @return
     *     possible object is
     *     {@link TextFieldType }
     *     
     */
    public TextFieldType getBookTitle() {
        return bookTitle;
    }

    /**
     * Sets the value of the bookTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextFieldType }
     *     
     */
    public void setBookTitle(TextFieldType value) {
        this.bookTitle = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationType }
     *     
     */
    public AnnotationType getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationType }
     *     
     */
    public void setAnnotation(AnnotationType value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link TextFieldType }
     *     
     */
    public TextFieldType getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextFieldType }
     *     
     */
    public void setKeywords(TextFieldType value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDate(DateType value) {
        this.date = value;
    }

    /**
     * Gets the value of the coverpage property.
     * 
     * @return
     *     possible object is
     *     {@link TitleInfoType.Coverpage }
     *     
     */
    public TitleInfoType.Coverpage getCoverpage() {
        return coverpage;
    }

    /**
     * Sets the value of the coverpage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleInfoType.Coverpage }
     *     
     */
    public void setCoverpage(TitleInfoType.Coverpage value) {
        this.coverpage = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }
    public void setLang(String value) {
        this.lang = value;
    }
    public String getSrcLang() {
        return srcLang;
    }
    public void setSrcLang(String value) {
        this.srcLang = value;
    }
    public List<AuthorType> getTranslator() {
        if (translator == null) {
            translator = new ArrayList<AuthorType>();
        }
        return this.translator;
    }

    public List<SequenceType> getSequence() {
        if (sequence == null) {
            sequence = new ArrayList<SequenceType>();
        }
        return this.sequence;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Author
        extends AuthorType
    {


    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "image"
    })
    public static class Coverpage {

        @XmlElement(required = true)
        protected List<InlineImageType> image;
        public List<InlineImageType> getImage() {
            if (image == null) {
                image = new ArrayList<InlineImageType>();
            }
            return this.image;
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Genre {

        @XmlValue
        protected GenreType value;
        @XmlAttribute(name = "match")
        protected BigInteger match;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link GenreType }
         *     
         */
        public GenreType getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link GenreType }
         *     
         */
        public void setValue(GenreType value) {
            this.value = value;
        }

        /**
         * Gets the value of the match property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMatch() {
            if (match == null) {
                return new BigInteger("100");
            } else {
                return match;
            }
        }

        /**
         * Sets the value of the match property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMatch(BigInteger value) {
            this.match = value;
        }

    }

}
